#!/usr/bin/env python3
"""Regenerate committed PNGs and FOX resources from the local SVG; requires rsvg-convert."""
from pathlib import Path
import hashlib
import subprocess
root = Path(__file__).resolve().parents[1]
master = root/'packaging/xfmd.svg'
output = root/'packaging/icons'
output.mkdir(exist_ok=True)
for size in (16,24,32,48,64,128):
    subprocess.run(['rsvg-convert','--width',str(size),'--height',str(size),'-o',str(output/f'xfmd-{size}.png'),str(master)],check=True)
lines = ['// Generated by tools/generate_icons.py. Do not edit.', '#pragma once',
         '// SVG SHA256: '+hashlib.sha256(master.read_bytes()).hexdigest(), 'namespace xfmd {']
for size in (16,64):
    data = (output/f'xfmd-{size}.png').read_bytes()
    lines.append(f'inline constexpr unsigned char icon{size}[] = {{')
    for i in range(0,len(data),16):
        lines.append('  '+','.join(f'0x{byte:02x}' for byte in data[i:i+16])+',')
    lines.append('};')
lines.append('} // namespace xfmd')
(root/'src/application/ui/IconData.h').write_text('\n'.join(lines)+'\n')
