find_package(Python3 REQUIRED COMPONENTS Interpreter)
function(xfmd_test name source)
  add_executable(${name} ${source})
  target_link_libraries(${name} PRIVATE xfmd_contracts ${ARGN})
  target_include_directories(${name} PRIVATE "${CMAKE_CURRENT_SOURCE_DIR}/tests")
  add_test(NAME ${name} COMMAND ${name})
  if(XFMD_SANITIZERS)
    set_tests_properties(${name} PROPERTIES ENVIRONMENT "LSAN_OPTIONS=suppressions=${CMAKE_CURRENT_SOURCE_DIR}/tests/support/lsan.supp;ASAN_OPTIONS=detect_leaks=1:halt_on_error=1;UBSAN_OPTIONS=halt_on_error=1:print_stacktrace=1")
  endif()
endfunction()
xfmd_test(PortContractTest tests/contracts/PortContractTest.cpp)
xfmd_test(DocumentTest tests/application/DocumentTest.cpp xfmd_document)
xfmd_test(FileOpenPolicyTest tests/application/FileOpenPolicyTest.cpp xfmd_document)
xfmd_test(InterpreterTest tests/interpreter/InterpreterTest.cpp xfmd_interpreter)
xfmd_test(RendererTest tests/renderer/RendererTest.cpp xfmd_interpreter xfmd_renderer)
xfmd_test(PreviewTest tests/application/PreviewTest.cpp xfmd_preview xfmd_renderer)
xfmd_test(ScrollTest tests/application/ScrollTest.cpp xfmd_scroll xfmd_interpreter xfmd_renderer)
xfmd_test(WorkPathTest tests/application/WorkPathTest.cpp xfmd_workspace)
xfmd_test(ExternalBrowserTest tests/application/ExternalBrowserTest.cpp xfmd_application)
xfmd_test(DocumentIndexTest tests/application/DocumentIndexTest.cpp xfmd_index xfmd_interpreter)
xfmd_test(ReferenceWorkerTest tests/application/ReferenceWorkerTest.cpp xfmd_index xfmd_interpreter)
xfmd_test(NavigationTest tests/application/NavigationTest.cpp xfmd_navigation)
add_test(NAME BlueprintStructure COMMAND ${Python3_EXECUTABLE} ${CMAKE_CURRENT_SOURCE_DIR}/tools/validate_blueprints.py)
add_test(NAME LayerBoundaries COMMAND ${Python3_EXECUTABLE} ${CMAKE_CURRENT_SOURCE_DIR}/tools/check_layers.py)
foreach(name PathWorkspaceGuiTest OpenPathDialogGuiTest FileRoutingGuiTest MermaidGuiTest RecentFilesGuiTest PreviewSelectionGuiTest CompactWorkspaceTest ReadingColorsGuiTest TreeActionsTest AppearancePreferencesTest AppearanceGuiTest UiControlsTest BrowserPreferencesTest IndexGuiTest WorkspaceTest PresentationTest ScrollingTest NavigationGuiTest SidebarGuiTest WheelGuiTest WorkPathGuiTest PointerTest TablePreviewTest)
  add_executable(${name} tests/gui/${name}.cpp)
  target_include_directories(${name} PRIVATE tests)
  target_link_libraries(${name} PRIVATE xfmd_application)
  target_compile_definitions(${name} PRIVATE XFMD_FIXTURE="${CMAKE_CURRENT_SOURCE_DIR}/tests/fixtures/markdown/basics.md")
  add_test(NAME ${name} COMMAND ${Python3_EXECUTABLE} ${CMAKE_CURRENT_SOURCE_DIR}/tools/run_with_xvfb.py $<TARGET_FILE:${name}>)
  set_tests_properties(${name} PROPERTIES TIMEOUT 65 LABELS GUI)
  if(XFMD_SANITIZERS)
    set_tests_properties(${name} PROPERTIES ENVIRONMENT "LSAN_OPTIONS=suppressions=${CMAKE_CURRENT_SOURCE_DIR}/tests/support/lsan.supp")
  endif()
endforeach()
add_executable(CapturePresentation tests/gui/CapturePresentation.cpp)
target_link_libraries(CapturePresentation PRIVATE xfmd_application)
target_compile_definitions(CapturePresentation PRIVATE XFMD_FIXTURE="${CMAKE_CURRENT_SOURCE_DIR}/tests/fixtures/markdown/basics.md")
add_executable(xfmd_benchmark tests/acceptance/Benchmark.cpp)
target_link_libraries(xfmd_benchmark PRIVATE xfmd_interpreter xfmd_renderer xfmd_typography)
add_executable(xfmd_cold_start tests/acceptance/ColdStart.cpp)
target_link_libraries(xfmd_cold_start PRIVATE xfmd_application)
find_program(STRACE_EXECUTABLE strace)
if(STRACE_EXECUTABLE AND NOT XFMD_SANITIZERS)
  add_executable(AtomicWriteFailure tests/acceptance/AtomicWriteFailure.cpp)
  target_link_libraries(AtomicWriteFailure PRIVATE xfmd_document)
  add_test(NAME DiskFullFailure COMMAND ${Python3_EXECUTABLE} ${CMAKE_CURRENT_SOURCE_DIR}/tools/check_disk_failure.py $<TARGET_FILE:AtomicWriteFailure>)
endif()
add_test(NAME BlueprintSymbols COMMAND ${Python3_EXECUTABLE} ${CMAKE_CURRENT_SOURCE_DIR}/tools/check_blueprint_symbols.py)
target_link_libraries(NavigationGuiTest PRIVATE X11::X11)
target_link_libraries(OpenPathDialogGuiTest PRIVATE X11::X11)
target_link_libraries(PathWorkspaceGuiTest PRIVATE X11::X11)
target_link_libraries(FileRoutingGuiTest PRIVATE X11::X11)
target_link_libraries(SidebarGuiTest PRIVATE X11::X11)

target_link_libraries(WheelGuiTest PRIVATE X11::X11)
target_link_libraries(WorkPathGuiTest PRIVATE X11::X11)
target_link_libraries(RecentFilesGuiTest PRIVATE X11::X11)

xfmd_test(ScrollMotionTest tests/application/ScrollMotionTest.cpp xfmd_scroll)

add_executable(PreferencesTest tests/application/PreferencesTest.cpp)
target_include_directories(PreferencesTest PRIVATE tests)
target_link_libraries(PreferencesTest PRIVATE xfmd_application)
add_test(NAME PreferencesTest COMMAND ${Python3_EXECUTABLE} ${CMAKE_CURRENT_SOURCE_DIR}/tools/run_with_xvfb.py $<TARGET_FILE:PreferencesTest>)
add_executable(TypographyFixture tests/acceptance/TypographyFixture.cpp)
target_include_directories(TypographyFixture PRIVATE tests)
target_link_libraries(TypographyFixture PRIVATE xfmd_typography xfmd_renderer xfmd_interpreter)
find_program(PDFTOTEXT_EXECUTABLE pdftotext)
find_program(PDFINFO_EXECUTABLE pdfinfo)
if(PDFTOTEXT_EXECUTABLE AND PDFINFO_EXECUTABLE)
  add_test(NAME TypographyTest COMMAND ${Python3_EXECUTABLE} ${CMAKE_CURRENT_SOURCE_DIR}/tools/check_typography.py $<TARGET_FILE:TypographyFixture>)
endif()
xfmd_test(PageLayoutTest tests/renderer/PageLayoutTest.cpp xfmd_renderer xfmd_interpreter xfmd_typography)
add_executable(PagedPreviewTest tests/gui/PagedPreviewTest.cpp)
target_include_directories(PagedPreviewTest PRIVATE tests)
target_link_libraries(PagedPreviewTest PRIVATE xfmd_application)
add_test(NAME PagedPreviewTest COMMAND ${Python3_EXECUTABLE} ${CMAKE_CURRENT_SOURCE_DIR}/tools/run_with_xvfb.py $<TARGET_FILE:PagedPreviewTest>)
set_tests_properties(PagedPreviewTest PROPERTIES TIMEOUT 30 LABELS GUI)

xfmd_test(ExportJobTest tests/application/ExportJobTest.cpp xfmd_export)

xfmd_test(PdfExportTest tests/application/PdfExportTest.cpp xfmd_export xfmd_interpreter xfmd_renderer)
add_executable(ExportGuiTest tests/gui/ExportGuiTest.cpp)
target_include_directories(ExportGuiTest PRIVATE tests)
target_link_libraries(ExportGuiTest PRIVATE xfmd_application)
add_test(NAME ExportGuiTest COMMAND ${Python3_EXECUTABLE} ${CMAKE_CURRENT_SOURCE_DIR}/tools/run_with_xvfb.py $<TARGET_FILE:ExportGuiTest>)
set_tests_properties(ExportGuiTest PROPERTIES TIMEOUT 30 LABELS GUI)

add_executable(PdfFidelityFixture tests/acceptance/PdfFidelityFixture.cpp)
target_include_directories(PdfFidelityFixture PRIVATE tests)
target_link_libraries(PdfFidelityFixture PRIVATE xfmd_export xfmd_interpreter xfmd_renderer)
find_program(PDFTOPPM_EXECUTABLE pdftoppm)
if(PDFTOTEXT_EXECUTABLE AND PDFINFO_EXECUTABLE AND PDFTOPPM_EXECUTABLE)
  add_test(NAME PdfFidelityTest COMMAND ${Python3_EXECUTABLE} ${CMAKE_CURRENT_SOURCE_DIR}/tools/check_pdf_fidelity.py $<TARGET_FILE:PdfFidelityFixture>)
  set_tests_properties(PdfFidelityTest PROPERTIES TIMEOUT 60)
endif()
if(STRACE_EXECUTABLE AND NOT XFMD_SANITIZERS)
  add_executable(PdfCommitFailure tests/acceptance/PdfCommitFailure.cpp)
  target_include_directories(PdfCommitFailure PRIVATE tests)
  target_link_libraries(PdfCommitFailure PRIVATE xfmd_export xfmd_interpreter xfmd_renderer)
  add_test(NAME PdfFlushFailure COMMAND ${Python3_EXECUTABLE} ${CMAKE_CURRENT_SOURCE_DIR}/tools/check_pdf_flush_failure.py $<TARGET_FILE:PdfCommitFailure>)
endif()
find_program(WMAKER_EXECUTABLE wmaker)
if(WMAKER_EXECUTABLE)
  add_executable(FullscreenTest tests/gui/FullscreenTest.cpp)
  target_include_directories(FullscreenTest PRIVATE tests)
  target_link_libraries(FullscreenTest PRIVATE xfmd_application)
  add_test(NAME FullscreenTest COMMAND ${Python3_EXECUTABLE} ${CMAKE_CURRENT_SOURCE_DIR}/tools/run_with_xvfb.py ${Python3_EXECUTABLE} ${CMAKE_CURRENT_SOURCE_DIR}/tools/run_with_wmaker.py $<TARGET_FILE:FullscreenTest>)
  set_tests_properties(FullscreenTest PROPERTIES TIMEOUT 60 LABELS GUI)
endif()
add_executable(IconTest tests/gui/IconTest.cpp)
target_include_directories(IconTest PRIVATE tests)
target_link_libraries(IconTest PRIVATE xfmd_application)
add_test(NAME IconTest COMMAND ${Python3_EXECUTABLE} ${CMAKE_CURRENT_SOURCE_DIR}/tools/run_with_xvfb.py $<TARGET_FILE:IconTest>)
set_tests_properties(IconTest PROPERTIES TIMEOUT 30 LABELS GUI)

add_executable(CanvasTest tests/gui/CanvasTest.cpp)
target_include_directories(CanvasTest PRIVATE tests)
target_link_libraries(CanvasTest PRIVATE xfmd_application)
add_test(NAME CanvasTest COMMAND ${Python3_EXECUTABLE} ${CMAKE_CURRENT_SOURCE_DIR}/tools/run_with_xvfb.py $<TARGET_FILE:CanvasTest>)
set_tests_properties(CanvasTest PROPERTIES TIMEOUT 30 LABELS GUI)

xfmd_test(TableTest tests/renderer/TableTest.cpp xfmd_renderer xfmd_interpreter xfmd_typography xfmd_scroll)
target_compile_definitions(TablePreviewTest PRIVATE XFMD_TABLE_FIXTURE="${CMAKE_CURRENT_SOURCE_DIR}/tests/fixtures/markdown/tables.md")
target_compile_definitions(TableTest PRIVATE XFMD_TABLE_FIXTURE="${CMAKE_CURRENT_SOURCE_DIR}/tests/fixtures/markdown/tables.md")

xfmd_test(ReadingColorsTest tests/application/ReadingColorsTest.cpp xfmd_typography xfmd_renderer xfmd_interpreter)

xfmd_test(RichPreviewTest tests/application/RichPreviewTest.cpp xfmd_export xfmd_media xfmd_typography xfmd_preview xfmd_interpreter xfmd_renderer)

if(XFMD_SANITIZERS)
  get_property(xfmd_tests DIRECTORY PROPERTY TESTS)
  set_tests_properties(${xfmd_tests} PROPERTIES ENVIRONMENT "LSAN_OPTIONS=suppressions=${CMAKE_CURRENT_SOURCE_DIR}/tests/support/lsan.supp;ASAN_OPTIONS=detect_leaks=1:halt_on_error=1;UBSAN_OPTIONS=halt_on_error=1:print_stacktrace=1")
endif()
add_executable(PdfBenchmark tests/acceptance/PdfBenchmark.cpp)
target_link_libraries(PdfBenchmark PRIVATE xfmd_export xfmd_interpreter xfmd_renderer)
add_executable(CapturePreferences tests/gui/CapturePreferences.cpp)
target_include_directories(CapturePreferences PRIVATE tests)
target_link_libraries(CapturePreferences PRIVATE xfmd_application)
xfmd_test(ThemeProfilesTest tests/application/ThemeProfilesTest.cpp xfmd_application)
add_executable(CaptureAppearance tests/gui/CaptureAppearance.cpp)
target_link_libraries(CaptureAppearance PRIVATE xfmd_application)
target_include_directories(CaptureAppearance PRIVATE tests)
target_compile_definitions(CaptureAppearance PRIVATE XFMD_FIXTURE="${CMAKE_CURRENT_SOURCE_DIR}/tests/fixtures/markdown/basics.md")

xfmd_test(DiagramLayoutTest tests/renderer/DiagramLayoutTest.cpp xfmd_interpreter xfmd_renderer xfmd_typography)
target_compile_definitions(DiagramLayoutTest PRIVATE XFMD_DIAGRAM_FIXTURES="${CMAKE_CURRENT_SOURCE_DIR}/docs/design/mermaid")
add_test(NAME MermaidRustTests COMMAND ${CARGO_EXECUTABLE} test --workspace --locked --offline --target-dir ${XFMD_CARGO_TARGET})
set_tests_properties(MermaidRustTests PROPERTIES WORKING_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}" TIMEOUT 180)
xfmd_test(DiagramPreparationTest tests/application/DiagramPreparationTest.cpp xfmd_diagrams)

set_tests_properties(WorkPathTest DiagramLayoutTest PROPERTIES TIMEOUT 30)
if(XFMD_SANITIZERS)
  # The suite exercises several layouts and includes sanitizer shutdown. Keep
  # per-layout deadline assertions in the test; allow diagnostics to finish.
  set_tests_properties(DiagramLayoutTest PROPERTIES TIMEOUT 90)
endif()

xfmd_test(DiagramReadingTest tests/application/DiagramReadingTest.cpp xfmd_diagrams xfmd_preview)
target_compile_definitions(DiagramReadingTest PRIVATE XFMD_SEQUENCE_FIXTURES="${CMAKE_CURRENT_SOURCE_DIR}/docs/design/mermaid")
add_executable(MermaidPdfFixture tests/acceptance/MermaidPdfFixture.cpp)
target_include_directories(MermaidPdfFixture PRIVATE tests)
target_link_libraries(MermaidPdfFixture PRIVATE xfmd_export)
target_compile_definitions(MermaidPdfFixture PRIVATE XFMD_DIAGRAM_FIXTURES="${CMAKE_CURRENT_SOURCE_DIR}/docs/design/mermaid")
add_test(NAME MermaidPdfTest COMMAND ${Python3_EXECUTABLE} ${CMAKE_CURRENT_SOURCE_DIR}/tools/check_mermaid_pdf.py $<TARGET_FILE:MermaidPdfFixture>)
if(XFMD_SANITIZERS)
  set_tests_properties(MermaidPdfTest PROPERTIES ENVIRONMENT "LSAN_OPTIONS=suppressions=${CMAKE_CURRENT_SOURCE_DIR}/tests/support/lsan.supp;ASAN_OPTIONS=detect_leaks=1:halt_on_error=1;UBSAN_OPTIONS=halt_on_error=1:print_stacktrace=1")
endif()

target_link_libraries(MermaidGuiTest PRIVATE X11::X11)

xfmd_test(DiagramWorkerTest tests/application/DiagramWorkerTest.cpp xfmd_preview xfmd_interpreter)
add_test(NAME MermaidDependencies COMMAND ${Python3_EXECUTABLE} ${CMAKE_CURRENT_SOURCE_DIR}/tools/check_mermaid_dependencies.py)
set_tests_properties(DiagramWorkerTest PROPERTIES TIMEOUT 10)

add_test(NAME BuildIdentityTest COMMAND ${Python3_EXECUTABLE} ${CMAKE_SOURCE_DIR}/tests/build/BuildIdentityTest.py)
add_test(NAME BuildVersionTest COMMAND ${Python3_EXECUTABLE} ${CMAKE_SOURCE_DIR}/tools/check_build_version.py $<TARGET_FILE:xfmd> ${XFMD_IDENTITY_DIR}/xfmd-build.json)

add_executable(DocumentViewsGuiTest tests/gui/DocumentViewsGuiTest.cpp)
target_include_directories(DocumentViewsGuiTest PRIVATE tests)
target_link_libraries(DocumentViewsGuiTest PRIVATE xfmd_application X11::X11)
if(DEFINED SDL_TOOL_EXECUTABLE)
  add_test(NAME DocumentViewsGuiTest COMMAND ${Python3_EXECUTABLE} ${CMAKE_CURRENT_SOURCE_DIR}/tools/run_with_xvfb.py $<TARGET_FILE:DocumentViewsGuiTest>)
  set_tests_properties(DocumentViewsGuiTest PROPERTIES ENVIRONMENT "SDL_TOOL=${SDL_TOOL_EXECUTABLE}" TIMEOUT 30 LABELS GUI)
endif()
add_test(NAME DocumentEndpointTest COMMAND ${Python3_EXECUTABLE} ${CMAKE_CURRENT_SOURCE_DIR}/tools/run_with_xvfb.py ${Python3_EXECUTABLE} ${CMAKE_CURRENT_SOURCE_DIR}/tests/gui/DocumentEndpointTest.py $<TARGET_FILE:xfmd>)
set_tests_properties(DocumentEndpointTest PROPERTIES TIMEOUT 30 LABELS GUI)

xfmd_test(WindowEndpointBoundaryTest tests/application/WindowEndpointBoundaryTest.cpp xfmd_application)
target_link_options(WindowEndpointBoundaryTest PRIVATE -Wl,--wrap=getsockopt)
add_executable(DocumentLeaseGuiTest tests/gui/DocumentLeaseGuiTest.cpp)
target_include_directories(DocumentLeaseGuiTest PRIVATE tests)
target_link_libraries(DocumentLeaseGuiTest PRIVATE xfmd_application)
target_link_options(DocumentLeaseGuiTest PRIVATE -Wl,--wrap=send)
add_test(NAME DocumentLeaseGuiTest COMMAND ${Python3_EXECUTABLE} ${CMAKE_CURRENT_SOURCE_DIR}/tools/run_with_xvfb.py $<TARGET_FILE:DocumentLeaseGuiTest>)
set_tests_properties(DocumentLeaseGuiTest PROPERTIES TIMEOUT 45 LABELS GUI)
if(XFMD_SANITIZERS)
  set_tests_properties(DocumentLeaseGuiTest PROPERTIES ENVIRONMENT "LSAN_OPTIONS=suppressions=${CMAKE_CURRENT_SOURCE_DIR}/tests/support/lsan.supp")
endif()

# XTEST exercises real server pointer routing/grabs in the palette popup.
if(TARGET X11::Xtst)
  add_executable(ThemePopupGuiTest tests/gui/ThemePopupGuiTest.cpp)
  target_include_directories(ThemePopupGuiTest PRIVATE tests)
  target_link_libraries(ThemePopupGuiTest PRIVATE xfmd_application X11::X11 X11::Xtst)
  add_test(NAME ThemePopupGuiTest COMMAND ${Python3_EXECUTABLE} ${CMAKE_CURRENT_SOURCE_DIR}/tools/run_with_xvfb.py $<TARGET_FILE:ThemePopupGuiTest>)
  set_tests_properties(ThemePopupGuiTest PROPERTIES TIMEOUT 65 LABELS GUI)
  if(XFMD_SANITIZERS)
    set_tests_properties(ThemePopupGuiTest PROPERTIES ENVIRONMENT "LSAN_OPTIONS=suppressions=${CMAKE_CURRENT_SOURCE_DIR}/tests/support/lsan.supp;ASAN_OPTIONS=detect_leaks=1:halt_on_error=1;UBSAN_OPTIONS=halt_on_error=1:print_stacktrace=1")
  endif()
endif()
