find_package(Python3 REQUIRED COMPONENTS Interpreter)
function(xfmd_test name source)
  add_executable(${name} ${source})
  target_link_libraries(${name} PRIVATE xfmd_contracts ${ARGN})
  target_include_directories(${name} PRIVATE "${CMAKE_CURRENT_SOURCE_DIR}/tests")
  add_test(NAME ${name} COMMAND ${name})
endfunction()
xfmd_test(PortContractTest tests/contracts/PortContractTest.cpp)
xfmd_test(DocumentTest tests/application/DocumentTest.cpp xfmd_document)
xfmd_test(InterpreterTest tests/interpreter/InterpreterTest.cpp xfmd_interpreter)
xfmd_test(RendererTest tests/renderer/RendererTest.cpp xfmd_interpreter xfmd_renderer)
xfmd_test(PreviewTest tests/application/PreviewTest.cpp xfmd_preview xfmd_renderer)
xfmd_test(ScrollTest tests/application/ScrollTest.cpp xfmd_scroll xfmd_interpreter xfmd_renderer)
xfmd_test(NavigationTest tests/application/NavigationTest.cpp xfmd_navigation)
add_test(NAME BlueprintStructure COMMAND ${Python3_EXECUTABLE} ${CMAKE_CURRENT_SOURCE_DIR}/tools/validate_blueprints.py)
add_test(NAME LayerBoundaries COMMAND ${Python3_EXECUTABLE} ${CMAKE_CURRENT_SOURCE_DIR}/tools/check_layers.py)
foreach(name WorkspaceTest PresentationTest ScrollingTest NavigationGuiTest SidebarGuiTest)
  add_executable(${name} tests/gui/${name}.cpp)
  target_include_directories(${name} PRIVATE tests)
  target_link_libraries(${name} PRIVATE xfmd_application)
  target_compile_definitions(${name} PRIVATE XFMD_FIXTURE="${CMAKE_CURRENT_SOURCE_DIR}/tests/fixtures/markdown/basics.md")
  add_test(NAME ${name} COMMAND ${Python3_EXECUTABLE} ${CMAKE_CURRENT_SOURCE_DIR}/tools/run_with_xvfb.py $<TARGET_FILE:${name}>)
  set_tests_properties(${name} PROPERTIES TIMEOUT 65 LABELS GUI)
  if(XFMD_SANITIZERS)
    set_tests_properties(${name} PROPERTIES ENVIRONMENT "LSAN_OPTIONS=suppressions=${CMAKE_CURRENT_SOURCE_DIR}/tests/support/lsan.supp")
  endif()
endforeach()
add_executable(CapturePresentation tests/gui/CapturePresentation.cpp)
target_link_libraries(CapturePresentation PRIVATE xfmd_application)
target_compile_definitions(CapturePresentation PRIVATE XFMD_FIXTURE="${CMAKE_CURRENT_SOURCE_DIR}/tests/fixtures/markdown/basics.md")
add_executable(xfmd_benchmark tests/acceptance/Benchmark.cpp src/application/adapters/FoxTextMetrics.cpp)
target_link_libraries(xfmd_benchmark PRIVATE xfmd_interpreter xfmd_renderer PkgConfig::FOX)
add_executable(xfmd_cold_start tests/acceptance/ColdStart.cpp)
target_link_libraries(xfmd_cold_start PRIVATE xfmd_application)
find_program(STRACE_EXECUTABLE strace)
if(STRACE_EXECUTABLE AND NOT XFMD_SANITIZERS)
  add_executable(AtomicWriteFailure tests/acceptance/AtomicWriteFailure.cpp)
  target_link_libraries(AtomicWriteFailure PRIVATE xfmd_document)
  add_test(NAME DiskFullFailure COMMAND ${Python3_EXECUTABLE} ${CMAKE_CURRENT_SOURCE_DIR}/tools/check_disk_failure.py $<TARGET_FILE:AtomicWriteFailure>)
endif()
add_test(NAME BlueprintSymbols COMMAND ${Python3_EXECUTABLE} ${CMAKE_CURRENT_SOURCE_DIR}/tools/check_blueprint_symbols.py)
find_package(X11 REQUIRED)
target_link_libraries(NavigationGuiTest PRIVATE X11::X11)
target_link_libraries(SidebarGuiTest PRIVATE X11::X11)
